### ISSUE TITLE
flash_attn_2_cuda error

### ISSUE THREAD

**Issue by abrakjamson** [Alpha-VLLM/Lumina-mGPT#9]
I've been wanting to try this project out, especially the omni model with freeform. I feel like I've resolved a dozen different issues, but this one has me stuck.

Windows 11
Nvidia 3060 12GB
CUDA 12.1

I've tried updating CUDA to 12.3, re-installing from requirements.txt, pre-compiled wheels for flash-attn, pre-compiled wheels for Triton, new Nvidia drivers, and probably other things.

Running the demo script yields this primary error:
```
RuntimeError: Failed to import model.chameleon.modeling_chameleon because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified procedure could not be found.
```

Here's the full trace path:
```
(lumina_mgpt) PS C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt> python -u .\demo_freeform.py
Traceback (most recent call last):
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\site-packages\transformers\utils\import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt\model\chameleon\modeling_chameleon.py", line 29, in <module>
    from transformers.modeling_flash_attention_utils import _flash_attention_forward
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\site-packages\transformers\modeling_flash_attention_utils.py", line 27, in <module>
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\site-packages\flash_attn\flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: The specified procedure could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt\demo_freeform.py", line 16, in <module>
    from inference_solver import FlexARInferenceSolver
  File "C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt\inference_solver.py", line 12, in <module>
    from data.item_processor import FlexARItemProcessor
  File "C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt\data\item_processor.py", line 10, in <module>
    import model.chameleon_vae_ori as chameleon_vae_ori
  File "C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt\model\__init__.py", line 2, in <module>
    from .modeling_xllmx_chameleon import ChameleonXLLMXForConditionalGeneration
  File "C:\Users\username\Downloads\Lumina-mGPT-main\Lumina-mGPT-main\lumina_mgpt\model\modeling_xllmx_chameleon.py", line 9, in <module>
    from .chameleon import ChameleonForConditionalGeneration
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\site-packages\transformers\utils\import_utils.py", line 1593, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\username\pinokio\bin\miniconda\envs\lumina_mgpt\lib\site-packages\transformers\utils\import_utils.py", line 1605, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import model.chameleon.modeling_chameleon because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified procedure could not be found.
```

Any ideas? Has anyone had success running on Windows?

**Comment by ChrisLiu6** [comment]
We don't have the experience installing flash-attention on windows but we do hear many people complain that it is miserable.  I guess an easier way would be passing the `attn_implementation='sdpa'` argument to model instantiation:

```
        model = ChameleonForConditionalGeneration.from_pretrained(
            model_path, torch_dtype=self.dtype, device_map="cuda",
            attn_implementation='sdpa'
        )
```

**Comment by abrakjamson** [comment]
That did it! After some more Torch version and CUDA_HOME wrangling, I got it running. Thank you for the help! By the way, the 768-Omni model will generate an image in about 6 hours on a 3060 12GB 🥲
